### ISSUE TITLE
Some changes has to be made for 2022

### ISSUE THREAD

**Issue by MAlfare** [desertplant/moon-phase-background#3]
The changes I have made:
```
Renamed old age.txt and phase.txt
Made new age.txt and phase.txt
Adapted moonback.sh. Changes are commented.
Left README.md unchanged
```
[moon-phase-background-main-2022.zip](https://github.com/desertplant/moon-phase-background/files/7797315/moon-phase-background-main-2022.zip)

**Comment by desertplant** [comment]
thank you, these changes are great. I've been meaning to update it for 2022, so thanks for doing it!

**Comment by desertplant** [comment]
Changes were added
