### ISSUE TITLE
Errors on execution

### ISSUE THREAD

**Issue by valenciakva** [desertplant/moon-phase-background#4]
I am receiving the following errors:

Hour of Year: 1648
Phase: 51.80
Alter: 7.892
Insert: Phase: 51.80% Days: 7.892
File to download: moon.1648.tif
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4647k  100 4647k    0     0  3407k      0  0:00:01  0:00:01 --:--:-- 3407k
/home/cava/Documents/moon-phase-background-main/moonback.sh: line 54: composite: command not found
/home/cava/Documents/moon-phase-background-main/moonback.sh: line 55: convert: command not found
/home/cava/Documents/moon-phase-background-main

Any help is appreciated,

**Comment by desertplant** [comment]
It sounds like you don't have ImageMagick installed. Could you try installing it and seeing if it works then?

**Comment by valenciakva** [comment]
Thanks for your prompt answer. I am sorry for my mistake. This solved the issue.

**Comment by desertplant** [comment]
No problem! Glad it works now. I hope you enjoy the script!
